import Head from "next/head"
import Link from "next/link"

export default function Home() {
	return (
		<div className="w-screen h-screen">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex gap-3 flex-col">
				<p>Página principal</p>
				<Link href="/posts/pca" >Páginas de posts</Link>
			</div>
		</div>
	)
}
