import Head from "next/head"
import Link from "next/link"

import { createServer } from "miragejs"
import { useEffect } from "react"

createServer({
  routes() {
    this.get("/api/movies", () => ({
      movies: [
        { id: 1, name: "Inception", year: 2010 },
        { id: 2, name: "Interstellar", year: 2014 },
        { id: 3, name: "Dunkirk", year: 2017 },
      ],
    }))
	this.passthrough()
  },
})

export default function Home() {
	useEffect(() => {
		fetch("/api/movies")
		  .then((res) => res.json())
		  .then((json) => {
			console.log(json.movies)
		  })
	  }, [])

	return (
		<div className="w-screen h-screen">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex gap-3 flex-col">
				<p>Página principal</p>
				<Link href="/posts/pca" >Páginas de posts</Link>
				<Link href="/login" >Login</Link>
			</div>
		</div>
	)
}
